// <auto-generated />
using System;
using Delopgaveprojekt.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Delopgaveprojekt.Migrations
{
    [DbContext(typeof(AppDbContext.AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Delopgaveprojekt.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("HVAnsaettelsedato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HVEfternavn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HVFagomraade")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HVFornavn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerkers");
                });

            modelBuilder.Entity("Delopgaveprojekt.Models.Vaerktoej", b =>
                {
                    b.Property<long>("VTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("LiggerIvtk")
                        .HasColumnType("int");

                    b.Property<int?>("LiggerIvtkNavigationVTKId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VTAnskaffet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VTFabrikat")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTSerienr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("VTId");

                    b.HasIndex("LiggerIvtkNavigationVTKId");

                    b.ToTable("Vaerktoejs");
                });

            modelBuilder.Entity("Delopgaveprojekt.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VTKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EjesAfNavigationHaandvaerkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VTKAnskaffet")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("VTKEjesAf")
                        .HasColumnType("int");

                    b.Property<string>("VTKFabrikat")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTKFarve")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTKModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VTKSerienummer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("VTKId");

                    b.HasIndex("EjesAfNavigationHaandvaerkerId");

                    b.ToTable("Vaerktoejskasses");
                });

            modelBuilder.Entity("Delopgaveprojekt.Models.Vaerktoej", b =>
                {
                    b.HasOne("Delopgaveprojekt.Models.Vaerktoejskasse", "LiggerIvtkNavigation")
                        .WithMany("Vaerktoej")
                        .HasForeignKey("LiggerIvtkNavigationVTKId");
                });

            modelBuilder.Entity("Delopgaveprojekt.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("Delopgaveprojekt.Models.Haandvaerker", "EjesAfNavigation")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("EjesAfNavigationHaandvaerkerId");
                });
#pragma warning restore 612, 618
        }
    }
}
