apiVersion: apps/v1
kind: Deployment
metadata:
  name: delopgaveprojektbackend-g9   
  labels:
    app: backend-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-g9
  template:
    metadata:
      labels:
        app: backend-g9
    spec:
      containers:
        - image: "docker.io/nichlaes/backendimage:latest"
          imagePullPolicy: Always
          name: backend-g9
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service-g9  
    labels: 
spec:
  selector:
    app: backend-g9
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: LoadBalancer
            