apiVersion: apps/v1
kind: Deployment
metadata:
  name: delopgaveprojektfrontend   
  labels:
    app: frontend-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-g9
  template:
    metadata:
      labels:
        app: frontend-g9
    spec:
      containers:
        - image: "docker.io/nichlaes/frontendimage:v1"
          imagePullPolicy: Always
          name: frontend-g9
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: delopgaveprojektfrontend  
    labels: 
spec:
  selector:
    app: frontend-g9
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
