FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TradedShares/TradedShares.csproj", "TradedShares/"]
RUN dotnet restore "TradedShares/TradedShares.csproj"
COPY . .
WORKDIR "/src/TradedShares"
RUN dotnet build "TradedShares.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TradedShares.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TradedShares.dll"]