apiVersion: apps/v1
kind: Deployment
metadata:
  name: TS-g9
  namespace: itonk-TSEIS-gr09
  labels:
    app: TS-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TS-g9
  template:
    metadata:
      labels:
        app: TS-g9
    spec:
      containers:
        - image: "docker.io/lostreidiotos/tsbackend:latest"
          imagePullPolicy: Always
          name: TS-g9
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: TS-service-g9
  labels:
spec:
  selector:
    app: TS-g9
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 80
  type: LoadBalancer
