apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttc-g9
  namespace: itonk-tseis-gr09
  labels:
    app: ttc-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttc-g9
  template:
    metadata:
      labels:
        app: ttc-g9
    spec:
      containers:
        - image: "docker.io/lostreidiotos/ttc:v1"
          imagePullPolicy: Always
          name: ttc-g9
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ttc-service-g9  
    labels: 
spec:
  selector:
    app: ttc-g9
  ports:
    - protocol: TCP
      port: 6973
      targetPort: 80
  type: LoadBalancer
            