apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-g9
  namespace: itonk-tseis-gr09
  labels:
    app: users-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-g9
  template:
    metadata:
      labels:
        app: users-g9
    spec:
      containers:
        - image: "docker.io/lostreidiotos/users:v1"
          imagePullPolicy: Always
          name: users-g9
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-g9
  labels:
spec:
  selector:
    app: users-g9
  ports:
    - protocol: TCP
      port: 6969
      targetPort: 80
  type: LoadBalancer
