apiVersion: apps/v1
kind: Deployment
metadata:
  name: stb-g9
  namespace: itonk-tseis-gr09
  labels:
    app: stb-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stb-g9
  template:
    metadata:
      labels:
        app: stb-g9
    spec:
      containers:
        - image: "docker.io/lostreidiotos/stb:v1"
          imagePullPolicy: Always
          name: stb-g9
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: stb-service-g9  
    labels: 
spec:
  selector:
    app: stb-g9
  ports:
    - protocol: TCP
      port: 6974
      targetPort: 80
  type: LoadBalancer
            