apiVersion: apps/v1
kind: Deployment
metadata:
  name: delopgaveprojektfrontend-g9  
  namespace: itonk-ap1-gr09 
  labels:
    app: frontend-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-g9
  template:
    metadata:
      labels:
        app: frontend-g9
    spec:
      containers:
        - image: "docker.io/nichlaes/frontendimage:latest"
          imagePullPolicy: Always
          name: frontend-g9
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service-g9  
    labels: 
spec:
  selector:
    app: frontend-g9
  ports:
    - protocol: TCP
      port: 69
      targetPort: 80
  type: LoadBalancer
