apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-g9-deployment
  namespace: itonk-tseis-gr09
  labels:
    app: mssql-g9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-g9
  template:
    metadata:
      labels:
        app: mssql-g9
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql-g9
        image: mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Group9database" 
        - name: MSSQL_DATA_DIR
          value: /var/opt/mssql/mdf
        - name: MSSQL_LOG_DIR
          value: /var/opt/mssql/ldf          
        volumeMounts:
        - name: mssql-base-volume-g9
          mountPath: /var/opt/mssql
        - name: mssql-ldf-volume-g9
          mountPath: /var/opt/mssql/ldf
        - name: mssql-mdf-volume-g9
          mountPath: /var/opt/mssql/mdf
      volumes:
      - name: mssql-base-volume-g9
        persistentVolumeClaim:
          claimName: mssql-base-volume-g9
      - name: mssql-mdf-volume-g9
        persistentVolumeClaim:
          claimName: mssql-mdf-volume-g9
      - name: mssql-ldf-volume-g9
        persistentVolumeClaim:
          claimName: mssql-ldf-volume-g9		  
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-g9
spec:
  selector:
    app: mssql-g9
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
    #mssql base volume claim: mssql-base-volume-g9.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-base-volume-g9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
#mssql data volume claim: mssql-mdf-volume-g9.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-mdf-volume-g9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
#mssql logs volume claim: mssql-ldf-volume-g9.yaml	  
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-ldf-volume-g9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi	  